# This rule is not used by the project apiserver itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to appscode.refat.kubebuilder.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: apiserver
    app.kubernetes.io/managed-by: kustomize
  name: apiserver-viewer-role
rules:
- apiGroups:
  - appscode.refat.kubebuilder.io
  resources:
  - apiservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appscode.refat.kubebuilder.io
  resources:
  - apiservers/status
  verbs:
  - get
