# This rule is not used by the project apiserver itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the appscode.refat.kubebuilder.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: apiserver
    app.kubernetes.io/managed-by: kustomize
  name: apiserver-editor-role
rules:
- apiGroups:
  - appscode.refat.kubebuilder.io
  resources:
  - apiservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appscode.refat.kubebuilder.io
  resources:
  - apiservers/status
  verbs:
  - get
